---
name: cf-redis
director_uuid: <%= `bosh status --uuid` %>

releases:
- name: cf-redis
  version: latest

compilation:
  cloud_properties:
    name: random
  network: services
  reuse_compilation_vms: true
  workers: 2

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 4

networks:
- name: services
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.3.32/30
    reserved:
    - 10.244.3.33
  - cloud_properties:
      name: random
    range: 10.244.3.36/30
    reserved:
    - 10.244.3.37
  - cloud_properties:
      name: random
    range: 10.244.3.40/30
    reserved:
    - 10.244.3.41
  - cloud_properties:
      name: random
    range: 10.244.3.44/30
    reserved:
    - 10.244.3.45
    static:
    - 10.244.3.46
  - cloud_properties:
      name: random
    range: 10.244.3.48/30
    reserved:
    - 10.244.3.49
  - cloud_properties:
      name: random
    range: 10.244.3.52/30
    reserved:
    - 10.244.3.53
    static:
    - 10.244.3.54
  - cloud_properties:
      name: random
    range: 10.244.3.56/30
    reserved:
    - 10.244.3.57
    static:
    - 10.244.3.58
  - cloud_properties:
      name: random
    range: 10.244.3.60/30
    reserved:
    - 10.244.3.61
    static:
    - 10.244.3.62
  - cloud_properties:
      name: random
    range: 10.244.3.64/30
    reserved:
    - 10.244.3.65
    static:
    - 10.244.3.66
  - cloud_properties:
      name: random
    range: 10.244.3.68/30
    reserved:
    - 10.244.3.69
    static:
    - 10.244.3.70

resource_pools:
- cloud_properties:
    ram: 1024
    name: random
  name: services-small
  network: services
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

jobs:
- name: dedicated-node
  templates:
  - name: dedicated-node
    release: cf-redis
  - name: syslog-configurator
    release: cf-redis
  instances: 1
  resource_pool: services-small
  persistent_disk: 4096
  networks:
  - name: services
    static_ips:
    - 10.244.3.54

properties:
  syslog_aggregator:
    address: 127.0.0.1
    port: 1234
  redis:
    host: 10.244.3.46
    maxmemory: 262144000
    config_command: config
    save_command: save
    bg_save_command: bgsave
